### ISSUE TITLE
Use the zmzimletctl per default

### ISSUE THREAD

**Issue by wolfyzvf** [Zimbra-Community/bulkreply-zimlet#1]
The _dev folder should not be the default option as it's for development purpose only.
By doing this, the zimlet will be recompiled each time the browser is refreshed that could lead to latency as you don't use the server cache and lead to a negative impact on the user experience.
Also, you loose the possibility to activate the zimlet per user/cos.

It would be better to have an install script that ask you if you are a developper or not and install it in the proper way.

**Comment by ghost** [comment]
I understand your point and you are very welcome to maintain and distribute the zip file for zmzimletctl, I however will not be doing that as this often results in people confronted with corrupted cache, who will then file invalid bugreports.
